//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bilgeOdev2.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public Nullable<int> BookId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<short> Salary { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<bool> IsMarried { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
